# Getting Started with NumPy

### Use the notebook to learn and later replace values with your own for practice

In [1]:
#import numpy
import numpy as np
#shift+enter to run code in a cell

In [2]:
#make an array(list) of ones
ones = np.ones(10)

In [3]:
#output the variable ones
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
#do arithmetic 
#notice it does not concatenate like a list would
ones + ones

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [5]:
#multiply by a scalar
ones * 3

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [6]:
#add a scalar
ones + 2

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [7]:
#make an array of 10 random numbers
rands = np.random.rand(10)
rands

array([0.85157739, 0.9789337 , 0.62759888, 0.11952596, 0.63513055,
       0.61056863, 0.33460011, 0.17457094, 0.48015453, 0.8190234 ])

In [8]:
#select an item in array just like a python list
rands[0]

0.8515773864024073

In [9]:
#can also do slices e.g give the first 3 elements
rands[:3]

array([0.85157739, 0.9789337 , 0.62759888])

In [10]:
#or give the last 3
rands[-3:]

array([0.17457094, 0.48015453, 0.8190234 ])

In [11]:
#select values based on quantities/properties 
#e.g give values in variable greater than 0.5
rands[np.where(rands > 0.5)]

array([0.85157739, 0.9789337 , 0.62759888, 0.63513055, 0.61056863,
       0.8190234 ])

In [12]:
#OR give values below 0.5
rands[np.where(rands < 0.5)]

array([0.11952596, 0.33460011, 0.17457094, 0.48015453])

In [13]:
#can add multiple array together
rands + ones

array([1.85157739, 1.9789337 , 1.62759888, 1.11952596, 1.63513055,
       1.61056863, 1.33460011, 1.17457094, 1.48015453, 1.8190234 ])

In [19]:
#can concatenate multiple arrays
np.concatenate((ones, rands))

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.85157739, 0.9789337 , 0.62759888, 0.11952596, 0.63513055,
       0.61056863, 0.33460011, 0.17457094, 0.48015453, 0.8190234 ])

In [16]:
#arrays can also be created based on lists/tuples of other arrays
np.array([1, 2, 3])

array([1, 2, 3])

In [17]:
#can also pass individual scalars numpy to arrays(ie creating)
np.array([ones, rands])
#similar to concatenate forms 2D array

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.85157739, 0.9789337 , 0.62759888, 0.11952596, 0.63513055,
        0.61056863, 0.33460011, 0.17457094, 0.48015453, 0.8190234 ]])

In [20]:
#can be indexed as if its a 1-Dimensional array but elements are np arrays
np.array([ones, rands])[0] #this gets ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.array([ones, rands])[1] #this gets rands array through indexing

array([0.85157739, 0.9789337 , 0.62759888, 0.11952596, 0.63513055,
       0.61056863, 0.33460011, 0.17457094, 0.48015453, 0.8190234 ])

In [23]:
#can also get slices from ones/rands /together 
np.array([ones, rands])[:, 0]

array([1.        , 0.85157739])

# Lists VS NumPy Array

In [28]:
#list of 10,000 values
my_list = range(int(1e4))
#np array of 10,000 values
my_array = np.arange(int(1e4))

In [ ]:
'''
    code below uses list comprehension 
    and timeit timing from jupyter and a line magic function
    to find and compare the speed of arithmetic operations 
    between python lists and NumPy arrays
'''

In [33]:
%%timeit
[i * 2 for i in my_list]

1.05 ms ± 16.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [36]:
%%timeit
my_array*2

15.4 µs ± 91.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
''' np array runs more than 10K faster than the list 
    because numpy does its backend work using optimised fortran and c compiled code
    in arrays it uses libraries originally used by supercomputers
'''